---
- name: Install Java 1.7
  apt: name=openjdk-7-jdk state=present
  sudo: True

- name: Install Ant
  apt: name=ant state=present
  sudo: True

- name: Install Unzip
  apt: name=unzip state=present
  sudo: True

# ADDING A NEW ACCOUNT
#- name: Add group "syndicate"
#  group: name=syndicate

#- name: Add user "syndicate"
#  user: name=syndicate group=syndicate home=/home/syndicate createhome=yes
#  sudo: True

- name: Download Hadoop CDH3U5
  get_url: url=http://archive.cloudera.com/cdh/3/hadoop-0.20.2-cdh3u5.tar.gz dest="{{ work_root }}/hadoop-0.20.2-cdh3u5.tar.gz"

- name: Uncompress Hadoop
  unarchive: src="{{ work_root }}/hadoop-0.20.2-cdh3u5.tar.gz" dest="{{ work_root }}/" copy=no

- name: Remove Hadoop if exists
  command: rm -rf "{{ work_root }}/hadoop"

- name: Rename Hadoop
  command: mv "{{ work_root }}/hadoop-0.20.2-cdh3u5" "{{ work_root }}/hadoop"

- name: Make Hadoop Data Dir
  file: path="{{ work_root }}/hdfs_data" state=directory

- name: Download H-Syndicate
  get_url: url=https://github.com/syndicate-storage/H-Syndicate/archive/master.zip dest="{{ work_root }}/h-syndicate.zip"

- name: Uncompress H-Syndicate
  unarchive: src="{{ work_root }}/h-syndicate.zip" dest=/home/iychoi/ copy=no

- name: Remove Hadoop if exists
  command: rm -rf "{{ work_root }}/h-syndicate"

- name: Rename H-Syndicate
  command: mv "{{ work_root }}/H-Syndicate-master" "{{ work_root }}/h-syndicate"

- name: Build H-Syndicate
  command: ant
  args:
    chdir: "{{ work_root }}/h-syndicate"

- name: Move H-Syndicate to Hadoop lib
  command: cp "{{ work_root }}/h-syndicate/dist/H-Syndicate.jar" "{{ work_root }}/hadoop/lib"

- name: Download Commons-collections
  get_url: url=http://central.maven.org/maven2/org/apache/commons/commons-collections4/4.0/commons-collections4-4.0.jar dest="{{ work_root }}/hadoop/lib/commons-collections4-4.0.jar"

- name: Download Jersey-client
  get_url: url=http://central.maven.org/maven2/com/sun/jersey/jersey-client/1.8/jersey-client-1.8.jar dest="{{ work_root }}/hadoop/lib/jersey-client-1.8.jar"

- name: Download Jackson-jaxrs
  get_url: url=http://central.maven.org/maven2/org/codehaus/jackson/jackson-jaxrs/1.5.2/jackson-jaxrs-1.5.2.jar dest="{{ work_root }}/hadoop/lib/jackson-jaxrs-1.5.2.jar"

- name: Download Jackson-xc
  get_url: url=http://central.maven.org/maven2/org/codehaus/jackson/jackson-xc/1.5.2/jackson-xc-1.5.2.jar dest="{{ work_root }}/hadoop/lib/jackson-xc-1.5.2.jar"


