---
- name: Configure Master
  template: src=masters dest="{{ work_root }}/hadoop/conf/"

- name: Configure Slave
  template: src=slaves dest="{{ work_root }}/hadoop/conf/"

- name: Hadoop Env
  template: src=hadoop-env.sh dest="{{ work_root }}/hadoop/conf/"

- name: core-Site
  template: src=core-site.xml dest="{{ work_root }}/hadoop/conf/"

- name: hdfs-Site
  template: src=hdfs-site.xml dest="{{ work_root }}/hadoop/conf/"

- name: mapred-site
  template: src=mapred-site.xml dest="{{ work_root }}/hadoop/conf/"

- name: Set JAVA_HOME
  lineinfile: dest="{{ work_root }}/.bashrc" line='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64' insertafter='EOF' regexp='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64' state=present

- name: Set HADOOP_HOME
  lineinfile: dest="{{ work_root }}/.bashrc" line='export HADOOP_HOME={{ work_root }}/hadoop' insertafter='EOF' regexp='export HADOOP_HOME={{ work_root }}/hadoop' state=present

